import Head from "next/head";
import { Inter } from "next/font/google";
import { Box, Heading, Link, Stack, Text, Image } from "@chakra-ui/react";
import { color } from "framer-motion";

const menuLists = [
  {
    id: 1,
    name: "CONTINUE (継続する)",
    url: "/",
    display: "true",
  },
  {
    id: 2,
    name: "GAME START (始める)",
    url: "/",
    display: "true",
  },
  {
    id: 3,
    name: "LOAD SAVE (データを読み込む)",
    url: "/",
    display: "true",
  },
  {
    id: 4,
    name: "EXTRA MODE (ギャラリー)",
    url: "/",
    display: "true",
  },
  {
    id: 5,
    name: "SETTINGS (設定)",
    url: "/",
    display: "true",
  },
  {
    id: 6,
    name: "EXIT GAME (ゲームを終了)",
    url: "/",
    display: "true",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        // minW="100vw"
        // minH="100vh"
        h={"643px"}
        w={"1366px"}
        bgImage="url('img/landingbg.jpg')"
        bgSize="cover"
        bgPos="center"
        position="relative"
      >
        {/* Gradient Overlay */}
        <Box
          position="absolute"
          top="0"
          left="0"
          width="100%"
          height="100%"
          backgroundImage="linear-gradient(90deg, #FFF 9.69%, rgba(255, 255, 255, 0.52) 59.71%, rgba(255, 255, 255, 0.00) 72.06%)"
          zIndex="1"
        />
        {/* Your content */}
        <Box zIndex={"2"} position={"absolute"}>
          <Image
            ml={"64px"}
            mt={"192px"}
            position={"absolute"}
            zIndex={"3"}
            src={"img/Menu.png"}
            alt="menu"
            width={"50%"}
          ></Image>
          <Image
            ml={"960px"}
            mt={"350px"}
            position={"absolute"}
            zIndex={"3"}
            src={"img/thedayilost.png"}
            alt="title"
          ></Image>
          <Stack gap={"24px"} mt={"280px"} ml={"72px"}>
            {menuLists.map((menuList) => {
              return (
                <Link
                  key={menuList.id}
                  href={menuList.url}
                  textDecoration={"none"}
                  color={"#848484"}
                  _hover={{ textDecoration: "none", color: "black" }}
                >
                  <Text fontSize={"xl"} fontWeight={"light"}>
                    {menuList.name}
                  </Text>
                </Link>
              );
            })}
          </Stack>
        </Box>
      </Box>
    </>
  );
}
